version: '3'

volumes:
  dbconfigfb:
  dblogfb:
  dbdatafb:

services:
  db:
    image: postgres:10.2-alpine
    ports:
      - "5432:5432"
    expose:
      - "5432"
    volumes:
      - "dbconfigfb:/etc/postgresql"
      - "dblogfb:/var/log/postgresql"
      - "dbdatafb:/var/lib/postgresql/data"
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pguser
      POSTGRES_DB: pgdb
  server:
    build: .
    ports:
      - "8081:8080"
    environment:
      HIBERNATE_FB_URL: jdbc:postgresql://db/pgdb
    depends_on:
      - db
